package vistas;

import javax.swing.JOptionPane;
import javax.swing.JTable;

import modelos.ListaPlatos;
import modelos.ModeloTablaPlato;
import modelos.Plato;

public class Principal extends javax.swing.JFrame {

    // Lista de platos que se cargan desde el fichero restaurante.csv
    private final ListaPlatos listaPlatos;

    public Principal() {
        listaPlatos = new ListaPlatos();
        initComponents();
        cargarDatosJTable();
    }

    // Este método inserta los datos de la lista en el jtable
    private void cargarDatosJTable() {

        ModeloTablaPlato modelo = new ModeloTablaPlato();
        int numColumnas = modelo.getColumnCount();

        for (Plato plato : listaPlatos.getPlatosConPrecioMayorQue(10.0)) {
            Object[] fila = new Object[numColumnas];
            fila[0] = plato.getIdPlato();
            fila[1] = plato.getNombre();
            fila[2] = plato.getDescripcion();
            fila[3] = plato.getPrecio();
            fila[4] = plato.isEsTemporada();
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    // Método para obtener la lista de platos cargada en el formulario desde el diálogo
    public ListaPlatos getListaPlatos() {
        return this.listaPlatos;
    }

    // Método para obtener el jtable del formulario
    // desde el diálogo
    public JTable getJTable() {
        return this.jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotonEditar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Platos");
        setBounds(new java.awt.Rectangle(150, 150, 0, 0));

        jScrollPane1.setViewportView(jTable1);

        BotonEditar.setText("Editar");
        BotonEditar.addActionListener((evt) -> {
            BotonEditarActionPerformed(evt);
        });

        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener((evt) -> {
            BotonActualizarActionPerformed(evt);
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener((evt) -> {
            BotonSalirActionPerformed(evt);
        });

        jLabel1.setText("Platos con precio mayor de 10€ (hasta 15 registros)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonSalir)
                    .addComponent(BotonActualizar)
                    .addComponent(BotonEditar))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonEditar)
                            .addComponent(BotonActualizar)
                            .addComponent(BotonSalir))
                        .addGap(70, 70, 70)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "No has seleccionado ningún registro");
        } else {
            new Editar(this, true).setVisible(true);
            cargarDatosJTable();
        }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "No has seleccionado ningún registro");
            return;
        }

        String idPlato = jTable1.getValueAt(fila, 0).toString();
        Object valor = jTable1.getValueAt(fila, 3);
        double precioNuevo;
        try {
            precioNuevo = Double.parseDouble(valor.toString());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Precio no válido. Introduce un número correcto.");
            return;
        }

        Plato plato = listaPlatos.getPlato(idPlato);
        plato.setPrecio(precioNuevo);
        cargarDatosJTable();
        JOptionPane.showMessageDialog(null, "Precio actualizado correctamente.");
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
